# Generated by Django 5.2.6 on 2025-09-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizer',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
